# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:16-alpine
orbs:
  node: circleci/node@5.1.0
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  setup_workspace:
    <<: *defaults
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - app
  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install Dependencies
          command: yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - app
  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: yarn test
          name: run unit tests
  build_to_s3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn run build
      - aws-s3/copy:
          from: build/
          to: s3://rotation27.com
          arguments: --recursive
workflows:
  test_and_deploy:
    jobs:
      - setup_workspace
      - install_dependencies:
          requires:
            - setup_workspace
      - unit_test:
          requires:
          - install_dependencies
      - build_to_s3:
          requires:
          - unit_test
